name: eslint, build, start

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run bundlesize
      - run: npm run start
