name: lint-and-build

on:
  pull_request:
    types: [opened]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun lint
      - run: npm run build
