name: eslint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: eslint
        run: npm run lint
